name: Build and Delivery

on:
  workflow_run:
    workflows: ["Test Python App"]
    branches: [main]
    types: [completed]

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      BUILD_CONTEXT: ${{ github.workspace }}/docker-build
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          path: docker-build
          
      - name: Build and push
        run: |
          cd ${{ github.workspace }}/docker-build
          docker build . -t westsunshine/my-app:latest
          docker push westsunshine/my-app:latest